# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asrInterface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QDialog, QPushButton, QLabel, QLineEdit
from PyQt5.QtGui import QMovie,QIntValidator
from PyQt5.QtCore import pyqtSignal



class Ui_MainWindow(object):
    content = 0
    content_2 = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 1000)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")


        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.linelabel = QtWidgets.QLabel(self.centralwidget)
        self.linelabel.setFont(font)
        self.linelabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.linelabel.setGeometry(QtCore.QRect(830, 300, 100, 40))
        self.linelabel.setObjectName("linelabel")

        self.linelabel3 = QtWidgets.QLabel(self.centralwidget)
        self.linelabel3.setFont(font)
        self.linelabel3.setHidden(True)
        self.linelabel3.setStyleSheet("color: rgb(255,23,140);")
        self.linelabel3.setGeometry(QtCore.QRect(1070, 300, 100, 40))
        self.linelabel3.setObjectName("linelabel3")

        self.countlabel = QtWidgets.QLabel(self.centralwidget)
        self.countlabel.setFont(font)
        self.countlabel.setStyleSheet("color: rgb(0,0,0)")
        self.countlabel.setGeometry(QtCore.QRect(780, 380, 120, 40))
        self.countlabel.setObjectName("countlabel")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setValidator(QIntValidator(1,5))
        self.lineEdit.setGeometry(QtCore.QRect(950, 300, 100, 40))
        self.lineEdit.setObjectName("lineEdit")


        self.label_200 = QtWidgets.QLabel(self.centralwidget)
        self.label_200.setGeometry(QtCore.QRect(55, 0, 70, 800))
        self.label_200.setStyleSheet("border-width: 3px;border-style: solid ;border-color: rgb(204, 232, 207);")
        self.label_200.setObjectName("label_200")

        self.label_300 = QtWidgets.QLabel(self.centralwidget)
        self.label_300.setGeometry(QtCore.QRect(175, 0, 70, 800))
        self.label_300.setStyleSheet("border-width: 3px;border-style: solid ;border-color: rgb(204, 232, 207);")
        self.label_300.setObjectName("label_300")

        self.label_400 = QtWidgets.QLabel(self.centralwidget)
        self.label_400.setGeometry(QtCore.QRect(295, 0, 70, 800))
        self.label_400.setStyleSheet("border-width: 3px;border-style: solid ;border-color: rgb(204, 232, 207);")
        self.label_400.setObjectName("label_400")

        self.label_500 = QtWidgets.QLabel(self.centralwidget)
        self.label_500.setGeometry(QtCore.QRect(415, 0, 70, 800))
        self.label_500.setStyleSheet("border-width: 3px;border-style: solid ;border-color: rgb(204, 232, 207);")
        self.label_500.setObjectName("label_500")

        self.label_600 = QtWidgets.QLabel(self.centralwidget)
        self.label_600.setGeometry(QtCore.QRect(535, 0, 70, 800))
        self.label_600.setStyleSheet("border-width: 3px;border-style: solid ;border-color: rgb(204, 232, 207);")
        self.label_600.setObjectName("label_600")

        self.labelbottom1 = QtWidgets.QPushButton(self.centralwidget)
        self.labelbottom1.setText("开门")
        self.labelbottom1.setGeometry(QtCore.QRect(55, 810, 30, 30))
        self.labelbottom1.setObjectName("labelbottom1")
        self.labelbottom2 = QtWidgets.QPushButton(self.centralwidget)
        self.labelbottom2.setText("关门")
        self.labelbottom2.setGeometry(QtCore.QRect(95, 810, 30, 30))
        self.labelbottom2.setObjectName("labelbottom2")

        self.labelbottom3 = QtWidgets.QPushButton(self.centralwidget)
        self.labelbottom3.setText("开门")
        self.labelbottom3.setGeometry(QtCore.QRect(175, 810, 30, 30))
        self.labelbottom3.setObjectName("labelbottom3")
        self.labelbottom4 = QtWidgets.QPushButton(self.centralwidget)
        self.labelbottom4.setText("关门")
        self.labelbottom4.setGeometry(QtCore.QRect(215, 810, 30, 30))
        self.labelbottom4.setObjectName("labelbottom4")

        self.labelbottom5 = QtWidgets.QPushButton(self.centralwidget)
        self.labelbottom5.setText("开门")
        self.labelbottom5.setGeometry(QtCore.QRect(295, 810, 30, 30))
        self.labelbottom5.setObjectName("labelbottom5")
        self.labelbottom6 = QtWidgets.QPushButton(self.centralwidget)
        self.labelbottom6.setText("关门")
        self.labelbottom6.setGeometry(QtCore.QRect(335, 810, 30, 30))
        self.labelbottom6.setObjectName("labelbottom6")

        self.labelbottom7 = QtWidgets.QPushButton(self.centralwidget)
        self.labelbottom7.setText("开门")
        self.labelbottom7.setGeometry(QtCore.QRect(415, 810, 30, 30))
        self.labelbottom7.setObjectName("labelbottom7")
        self.labelbottom8 = QtWidgets.QPushButton(self.centralwidget)
        self.labelbottom8.setText("关门")
        self.labelbottom8.setGeometry(QtCore.QRect(455, 810, 30, 30))
        self.labelbottom8.setObjectName("labelbottom8")

        self.labelbottom9 = QtWidgets.QPushButton(self.centralwidget)
        self.labelbottom9.setText("开门")
        self.labelbottom9.setGeometry(QtCore.QRect(535, 810, 30, 30))
        self.labelbottom9.setObjectName("labelbottom9")
        self.labelbottom0 = QtWidgets.QPushButton(self.centralwidget)
        self.labelbottom0.setText("关门")
        self.labelbottom0.setGeometry(QtCore.QRect(575, 810, 30, 30))
        self.labelbottom0.setObjectName("labelbottom0")

        self.outbutton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_1.setText("上")
        self.outbutton_1.setGeometry(QtCore.QRect(680, 45, 30, 30))
        self.outbutton_1.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_1.setObjectName("outbutton_1")
        self.outbutton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_2.setText("上")
        self.outbutton_2.setGeometry(QtCore.QRect(680, 85, 30, 30))
        self.outbutton_2.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_2.setObjectName("outbutton_2")
        self.outbutton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_3.setText("上")
        self.outbutton_3.setGeometry(QtCore.QRect(680, 125, 30, 30))
        self.outbutton_3.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_3.setObjectName("outbutton_3")
        self.outbutton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_4.setText("上")
        self.outbutton_4.setGeometry(QtCore.QRect(680, 165, 30, 30))
        self.outbutton_4.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_4.setObjectName("outbutton_4")
        self.outbutton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_5.setText("上")
        self.outbutton_5.setGeometry(QtCore.QRect(680, 205, 30, 30))
        self.outbutton_5.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_5.setObjectName("outbutton_5")
        self.outbutton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_6.setText("上")
        self.outbutton_6.setGeometry(QtCore.QRect(680, 245, 30, 30))
        self.outbutton_6.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_6.setObjectName("outbutton_6")
        self.outbutton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_7.setText("上")
        self.outbutton_7.setGeometry(QtCore.QRect(680, 285, 30, 30))
        self.outbutton_7.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_7.setObjectName("outbutton_7")
        self.outbutton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_8.setText("上")
        self.outbutton_8.setGeometry(QtCore.QRect(680, 325, 30, 30))
        self.outbutton_8.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_8.setObjectName("outbutton_8")
        self.outbutton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_9.setText("上")
        self.outbutton_9.setGeometry(QtCore.QRect(680, 365, 30, 30))
        self.outbutton_9.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_9.setObjectName("outbutton_9")
        self.outbutton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_10.setText("上")
        self.outbutton_10.setGeometry(QtCore.QRect(680, 405, 30, 30))
        self.outbutton_10.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_10.setObjectName("outbutton_10")
        self.outbutton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_11.setText("上")
        self.outbutton_11.setGeometry(QtCore.QRect(680, 445, 30, 30))
        self.outbutton_11.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_11.setObjectName("outbutton_11")
        self.outbutton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_12.setText("上")
        self.outbutton_12.setGeometry(QtCore.QRect(680, 485, 30, 30))
        self.outbutton_12.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_12.setObjectName("outbutton_12")
        self.outbutton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_13.setText("上")
        self.outbutton_13.setGeometry(QtCore.QRect(680, 525, 30, 30))
        self.outbutton_13.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_13.setObjectName("outbutton_13")
        self.outbutton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_14.setText("上")
        self.outbutton_14.setGeometry(QtCore.QRect(680, 565, 30, 30))
        self.outbutton_14.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_14.setObjectName("outbutton_14")
        self.outbutton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_15.setText("上")
        self.outbutton_15.setGeometry(QtCore.QRect(680, 605, 30, 30))
        self.outbutton_15.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_15.setObjectName("outbutton_15")
        self.outbutton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_16.setText("上")
        self.outbutton_16.setGeometry(QtCore.QRect(680, 645, 30, 30))
        self.outbutton_16.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_16.setObjectName("outbutton_16")
        self.outbutton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_17.setText("上")
        self.outbutton_17.setGeometry(QtCore.QRect(680, 685, 30, 30))
        self.outbutton_17.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_17.setObjectName("outbutton_17")
        self.outbutton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_18.setText("上")
        self.outbutton_18.setGeometry(QtCore.QRect(680, 725, 30, 30))
        self.outbutton_18.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_18.setObjectName("outbutton_18")
        self.outbutton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_19.setText("上")
        self.outbutton_19.setGeometry(QtCore.QRect(680, 765, 30, 30))
        self.outbutton_19.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_19.setObjectName("outbutton_19")
        self.outbutton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_20.setText("下")
        self.outbutton_20.setGeometry(QtCore.QRect(720, 5, 30, 30))
        self.outbutton_20.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_20.setObjectName("outbutton_20")
        self.outbutton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_21.setText("下")
        self.outbutton_21.setGeometry(QtCore.QRect(720, 45, 30, 30))
        self.outbutton_21.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_21.setObjectName("outbutton_21")
        self.outbutton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_22.setText("下")
        self.outbutton_22.setGeometry(QtCore.QRect(720, 85, 30, 30))
        self.outbutton_22.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_22.setObjectName("outbutton_22")
        self.outbutton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_23.setText("下")
        self.outbutton_23.setGeometry(QtCore.QRect(720, 125, 30, 30))
        self.outbutton_23.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_23.setObjectName("outbutton_23")
        self.outbutton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_24.setText("下")
        self.outbutton_24.setGeometry(QtCore.QRect(720, 165, 30, 30))
        self.outbutton_24.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_24.setObjectName("outbutton_24")
        self.outbutton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_25.setText("下")
        self.outbutton_25.setGeometry(QtCore.QRect(720, 205, 30, 30))
        self.outbutton_25.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_25.setObjectName("outbutton_25")
        self.outbutton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_26.setText("下")
        self.outbutton_26.setGeometry(QtCore.QRect(720, 245, 30, 30))
        self.outbutton_26.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_26.setObjectName("outbutton_26")
        self.outbutton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_27.setText("下")
        self.outbutton_27.setGeometry(QtCore.QRect(720, 285, 30, 30))
        self.outbutton_27.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_27.setObjectName("outbutton_27")
        self.outbutton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_28.setText("下")
        self.outbutton_28.setGeometry(QtCore.QRect(720, 325, 30, 30))
        self.outbutton_28.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_28.setObjectName("outbutton_28")
        self.outbutton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_29.setText("下")
        self.outbutton_29.setGeometry(QtCore.QRect(720, 365, 30, 30))
        self.outbutton_29.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_29.setObjectName("outbutton_29")
        self.outbutton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_30.setText("下")
        self.outbutton_30.setGeometry(QtCore.QRect(720, 405, 30, 30))
        self.outbutton_30.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_30.setObjectName("outbutton_30")
        self.outbutton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_31.setText("下")
        self.outbutton_31.setGeometry(QtCore.QRect(720, 445, 30, 30))
        self.outbutton_31.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_31.setObjectName("outbutton_31")
        self.outbutton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_32.setText("下")
        self.outbutton_32.setGeometry(QtCore.QRect(720, 485, 30, 30))
        self.outbutton_32.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_32.setObjectName("outbutton_32")
        self.outbutton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_33.setText("下")
        self.outbutton_33.setGeometry(QtCore.QRect(720, 525, 30, 30))
        self.outbutton_33.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_33.setObjectName("outbutton_33")
        self.outbutton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_34.setText("下")
        self.outbutton_34.setGeometry(QtCore.QRect(720, 565, 30, 30))
        self.outbutton_34.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_34.setObjectName("outbutton_34")
        self.outbutton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_35.setText("下")
        self.outbutton_35.setGeometry(QtCore.QRect(720, 605, 30, 30))
        self.outbutton_35.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_35.setObjectName("outbutton_35")
        self.outbutton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_36.setText("下")
        self.outbutton_36.setGeometry(QtCore.QRect(720, 645, 30, 30))
        self.outbutton_36.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_36.setObjectName("outbutton_36")
        self.outbutton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_37.setText("下")
        self.outbutton_37.setGeometry(QtCore.QRect(720, 685, 30, 30))
        self.outbutton_37.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_37.setObjectName("outbutton_37")
        self.outbutton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.outbutton_38.setText("下")
        self.outbutton_38.setGeometry(QtCore.QRect(720, 725, 30, 30))
        self.outbutton_38.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 150);")
        self.outbutton_38.setObjectName("outbutton_38")

        self.label_21 = QtWidgets.QPushButton(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(60, 5, 60, 30))
        self.label_21.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_21.setText("20")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QPushButton(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(60, 45, 60, 30))
        self.label_22.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_22.setText("19")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QPushButton(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(60, 85, 60, 30))
        self.label_23.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_23.setText("18")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QPushButton(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(60, 125, 60, 30))
        self.label_24.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_24.setText("17")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QPushButton(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(60, 165, 60, 30))
        self.label_25.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_25.setText("16")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QPushButton(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(60, 205, 60, 30))
        self.label_26.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_26.setText("15")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QPushButton(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(60, 245, 60, 30))
        self.label_27.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_27.setText("14")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QPushButton(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(60, 285, 60, 30))
        self.label_28.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_28.setText("13")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QPushButton(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(60, 325, 60, 30))
        self.label_29.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_29.setText("12")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QPushButton(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(60, 365, 60, 30))
        self.label_30.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_30.setText("11")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QPushButton(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(60, 405, 60, 30))
        self.label_31.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_31.setText("10")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QPushButton(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(60, 445, 60, 30))
        self.label_32.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_32.setText("9")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QPushButton(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(60, 485, 60, 30))
        self.label_33.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_33.setText("8")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QPushButton(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(60, 525, 60, 30))
        self.label_34.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_34.setText("7")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QPushButton(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(60, 565, 60, 30))
        self.label_35.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_35.setText("6")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QPushButton(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(60, 605, 60, 30))
        self.label_36.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_36.setText("5")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QPushButton(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(60, 645, 60, 30))
        self.label_37.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_37.setText("4")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QPushButton(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(60, 685, 60, 30))
        self.label_38.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_38.setText("3")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QPushButton(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(60, 725, 60, 30))
        self.label_39.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_39.setText("2")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QPushButton(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(60, 765, 60, 30))
        self.label_40.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_40.setText("1")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QPushButton(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(180, 5, 60, 30))
        self.label_41.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_41.setText("20")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QPushButton(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(180, 45, 60, 30))
        self.label_42.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_42.setText("19")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QPushButton(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(180, 85, 60, 30))
        self.label_43.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_43.setText("18")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QPushButton(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(180, 125, 60, 30))
        self.label_44.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_44.setText("17")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QPushButton(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(180, 165, 60, 30))
        self.label_45.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_45.setText("16")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QPushButton(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(180, 205, 60, 30))
        self.label_46.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_46.setText("15")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QPushButton(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(180, 245, 60, 30))
        self.label_47.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_47.setText("14")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QPushButton(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(180, 285, 60, 30))
        self.label_48.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_48.setText("13")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QPushButton(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(180, 325, 60, 30))
        self.label_49.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_49.setText("12")
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QPushButton(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(180, 365, 60, 30))
        self.label_50.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_50.setText("11")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QPushButton(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(180, 405, 60, 30))
        self.label_51.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_51.setText("10")
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QPushButton(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(180, 445, 60, 30))
        self.label_52.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_52.setText("9")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QPushButton(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(180, 485, 60, 30))
        self.label_53.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_53.setText("8")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QPushButton(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(180, 525, 60, 30))
        self.label_54.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_54.setText("7")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QPushButton(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(180, 565, 60, 30))
        self.label_55.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_55.setText("6")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QPushButton(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(180, 605, 60, 30))
        self.label_56.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_56.setText("5")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QPushButton(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(180, 645, 60, 30))
        self.label_57.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_57.setText("4")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QPushButton(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(180, 685, 60, 30))
        self.label_58.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_58.setText("3")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QPushButton(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(180, 725, 60, 30))
        self.label_59.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_59.setText("2")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QPushButton(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(180, 765, 60, 30))
        self.label_60.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_60.setText("1")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QPushButton(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(300, 5, 60, 30))
        self.label_61.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_61.setText("20")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QPushButton(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(300, 45, 60, 30))
        self.label_62.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_62.setText("19")
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QPushButton(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(300, 85, 60, 30))
        self.label_63.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_63.setText("18")
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QPushButton(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(300, 125, 60, 30))
        self.label_64.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_64.setText("17")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QPushButton(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(300, 165, 60, 30))
        self.label_65.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_65.setText("16")
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QPushButton(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(300, 205, 60, 30))
        self.label_66.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_66.setText("15")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QPushButton(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(300, 245, 60, 30))
        self.label_67.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_67.setText("14")
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QPushButton(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(300, 285, 60, 30))
        self.label_68.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_68.setText("13")
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QPushButton(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(300, 325, 60, 30))
        self.label_69.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_69.setText("12")
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QPushButton(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(300, 365, 60, 30))
        self.label_70.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_70.setText("11")
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QPushButton(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(300, 405, 60, 30))
        self.label_71.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_71.setText("10")
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QPushButton(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(300, 445, 60, 30))
        self.label_72.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_72.setText("9")
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QPushButton(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(300, 485, 60, 30))
        self.label_73.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_73.setText("8")
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QPushButton(self.centralwidget)
        self.label_74.setGeometry(QtCore.QRect(300, 525, 60, 30))
        self.label_74.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_74.setText("7")
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QPushButton(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(300, 565, 60, 30))
        self.label_75.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_75.setText("6")
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QPushButton(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(300, 605, 60, 30))
        self.label_76.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_76.setText("5")
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QPushButton(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(300, 645, 60, 30))
        self.label_77.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_77.setText("4")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QPushButton(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(300, 685, 60, 30))
        self.label_78.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_78.setText("3")
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QPushButton(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(300, 725, 60, 30))
        self.label_79.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_79.setText("2")
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QPushButton(self.centralwidget)
        self.label_80.setGeometry(QtCore.QRect(300, 765, 60, 30))
        self.label_80.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_80.setText("1")
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QPushButton(self.centralwidget)
        self.label_81.setGeometry(QtCore.QRect(420, 5, 60, 30))
        self.label_81.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_81.setText("20")
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QPushButton(self.centralwidget)
        self.label_82.setGeometry(QtCore.QRect(420, 45, 60, 30))
        self.label_82.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_82.setText("19")
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QPushButton(self.centralwidget)
        self.label_83.setGeometry(QtCore.QRect(420, 85, 60, 30))
        self.label_83.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_83.setText("18")
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QPushButton(self.centralwidget)
        self.label_84.setGeometry(QtCore.QRect(420, 125, 60, 30))
        self.label_84.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_84.setText("17")
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QPushButton(self.centralwidget)
        self.label_85.setGeometry(QtCore.QRect(420, 165, 60, 30))
        self.label_85.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_85.setText("16")
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QPushButton(self.centralwidget)
        self.label_86.setGeometry(QtCore.QRect(420, 205, 60, 30))
        self.label_86.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_86.setText("15")
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QPushButton(self.centralwidget)
        self.label_87.setGeometry(QtCore.QRect(420, 245, 60, 30))
        self.label_87.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_87.setText("14")
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QPushButton(self.centralwidget)
        self.label_88.setGeometry(QtCore.QRect(420, 285, 60, 30))
        self.label_88.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_88.setText("13")
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QPushButton(self.centralwidget)
        self.label_89.setGeometry(QtCore.QRect(420, 325, 60, 30))
        self.label_89.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_89.setText("12")
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QPushButton(self.centralwidget)
        self.label_90.setGeometry(QtCore.QRect(420, 365, 60, 30))
        self.label_90.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_90.setText("11")
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QPushButton(self.centralwidget)
        self.label_91.setGeometry(QtCore.QRect(420, 405, 60, 30))
        self.label_91.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_91.setText("10")
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QPushButton(self.centralwidget)
        self.label_92.setGeometry(QtCore.QRect(420, 445, 60, 30))
        self.label_92.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_92.setText("9")
        self.label_92.setObjectName("label_92")
        self.label_93 = QtWidgets.QPushButton(self.centralwidget)
        self.label_93.setGeometry(QtCore.QRect(420, 485, 60, 30))
        self.label_93.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_93.setText("8")
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QPushButton(self.centralwidget)
        self.label_94.setGeometry(QtCore.QRect(420, 525, 60, 30))
        self.label_94.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_94.setText("7")
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QPushButton(self.centralwidget)
        self.label_95.setGeometry(QtCore.QRect(420, 565, 60, 30))
        self.label_95.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_95.setText("6")
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QPushButton(self.centralwidget)
        self.label_96.setGeometry(QtCore.QRect(420, 605, 60, 30))
        self.label_96.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_96.setText("5")
        self.label_96.setObjectName("label_96")
        self.label_97 = QtWidgets.QPushButton(self.centralwidget)
        self.label_97.setGeometry(QtCore.QRect(420, 645, 60, 30))
        self.label_97.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_97.setText("4")
        self.label_97.setObjectName("label_97")
        self.label_98 = QtWidgets.QPushButton(self.centralwidget)
        self.label_98.setGeometry(QtCore.QRect(420, 685, 60, 30))
        self.label_98.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_98.setText("3")
        self.label_98.setObjectName("label_98")
        self.label_99 = QtWidgets.QPushButton(self.centralwidget)
        self.label_99.setGeometry(QtCore.QRect(420, 725, 60, 30))
        self.label_99.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_99.setText("2")
        self.label_99.setObjectName("label_99")
        self.label_100 = QtWidgets.QPushButton(self.centralwidget)
        self.label_100.setGeometry(QtCore.QRect(420, 765, 60, 30))
        self.label_100.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_100.setText("1")
        self.label_100.setObjectName("label_100")
        self.label_101 = QtWidgets.QPushButton(self.centralwidget)
        self.label_101.setGeometry(QtCore.QRect(540, 5, 60, 30))
        self.label_101.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_101.setText("20")
        self.label_101.setObjectName("label_101")
        self.label_102 = QtWidgets.QPushButton(self.centralwidget)
        self.label_102.setGeometry(QtCore.QRect(540, 45, 60, 30))
        self.label_102.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_102.setText("19")
        self.label_102.setObjectName("label_102")
        self.label_103 = QtWidgets.QPushButton(self.centralwidget)
        self.label_103.setGeometry(QtCore.QRect(540, 85, 60, 30))
        self.label_103.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_103.setText("18")
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QPushButton(self.centralwidget)
        self.label_104.setGeometry(QtCore.QRect(540, 125, 60, 30))
        self.label_104.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_104.setText("17")
        self.label_104.setObjectName("label_104")
        self.label_105 = QtWidgets.QPushButton(self.centralwidget)
        self.label_105.setGeometry(QtCore.QRect(540, 165, 60, 30))
        self.label_105.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_105.setText("16")
        self.label_105.setObjectName("label_105")
        self.label_106 = QtWidgets.QPushButton(self.centralwidget)
        self.label_106.setGeometry(QtCore.QRect(540, 205, 60, 30))
        self.label_106.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_106.setText("15")
        self.label_106.setObjectName("label_106")
        self.label_107 = QtWidgets.QPushButton(self.centralwidget)
        self.label_107.setGeometry(QtCore.QRect(540, 245, 60, 30))
        self.label_107.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_107.setText("14")
        self.label_107.setObjectName("label_107")
        self.label_108 = QtWidgets.QPushButton(self.centralwidget)
        self.label_108.setGeometry(QtCore.QRect(540, 285, 60, 30))
        self.label_108.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_108.setText("13")
        self.label_108.setObjectName("label_108")
        self.label_109 = QtWidgets.QPushButton(self.centralwidget)
        self.label_109.setGeometry(QtCore.QRect(540, 325, 60, 30))
        self.label_109.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_109.setText("12")
        self.label_109.setObjectName("label_109")
        self.label_110 = QtWidgets.QPushButton(self.centralwidget)
        self.label_110.setGeometry(QtCore.QRect(540, 365, 60, 30))
        self.label_110.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_110.setText("11")
        self.label_110.setObjectName("label_110")
        self.label_111 = QtWidgets.QPushButton(self.centralwidget)
        self.label_111.setGeometry(QtCore.QRect(540, 405, 60, 30))
        self.label_111.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_111.setText("10")
        self.label_111.setObjectName("label_111")
        self.label_112 = QtWidgets.QPushButton(self.centralwidget)
        self.label_112.setGeometry(QtCore.QRect(540, 445, 60, 30))
        self.label_112.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_112.setText("9")
        self.label_112.setObjectName("label_112")
        self.label_113 = QtWidgets.QPushButton(self.centralwidget)
        self.label_113.setGeometry(QtCore.QRect(540, 485, 60, 30))
        self.label_113.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_113.setText("8")
        self.label_113.setObjectName("label_113")
        self.label_114 = QtWidgets.QPushButton(self.centralwidget)
        self.label_114.setGeometry(QtCore.QRect(540, 525, 60, 30))
        self.label_114.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_114.setText("7")
        self.label_114.setObjectName("label_114")
        self.label_115 = QtWidgets.QPushButton(self.centralwidget)
        self.label_115.setGeometry(QtCore.QRect(540, 565, 60, 30))
        self.label_115.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_115.setText("6")
        self.label_115.setObjectName("label_115")
        self.label_116 = QtWidgets.QPushButton(self.centralwidget)
        self.label_116.setGeometry(QtCore.QRect(540, 605, 60, 30))
        self.label_116.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_116.setText("5")
        self.label_116.setObjectName("label_116")
        self.label_117 = QtWidgets.QPushButton(self.centralwidget)
        self.label_117.setGeometry(QtCore.QRect(540, 645, 60, 30))
        self.label_117.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_117.setText("4")
        self.label_117.setObjectName("label_117")
        self.label_118 = QtWidgets.QPushButton(self.centralwidget)
        self.label_118.setGeometry(QtCore.QRect(540, 685, 60, 30))
        self.label_118.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_118.setText("3")
        self.label_118.setObjectName("label_118")
        self.label_119 = QtWidgets.QPushButton(self.centralwidget)
        self.label_119.setGeometry(QtCore.QRect(540, 725, 60, 30))
        self.label_119.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_119.setText("2")
        self.label_119.setObjectName("label_119")
        self.label_120 = QtWidgets.QPushButton(self.centralwidget)
        self.label_120.setGeometry(QtCore.QRect(540, 765, 60, 30))
        self.label_120.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(255, 170, 0);")
        self.label_120.setText("1")
        self.label_120.setObjectName("label_120")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lift Control"))
        self.linelabel.setText(_translate("MainWindow", "电梯序号："))
        self.linelabel3.setText(_translate("MainWindow", "不得为空(0)"))



    def showtext(self):
        if (self.lineEdit.text()):
            self.content = self.lineEdit.text()
        else:
            self.content = 0

